# Generated by Django 5.2 on 2025-05-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='参与考核部门')),
            ],
        ),
        migrations.CreateModel(
            name='MusicTeacherAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '艺术教师考核成绩',
                'verbose_name_plural': '艺术教师考核成绩',
            },
        ),
        migrations.CreateModel(
            name='TermType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.CharField(choices=[('mid', '期中考试'), ('final', '期末考试'), ('semester', '学期总评')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='学年')),
                ('semester_type', models.CharField(choices=[('last', '上学期'), ('next', '下学期')], max_length=20)),
            ],
            options={
                'unique_together': {('year', 'semester_type')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFinalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week', models.IntegerField()),
                ('class_hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='课时节数')),
                ('duty_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='值班节数折算')),
                ('extra_work_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='额外工作节数折算')),
                ('total_workload', models.FloatField(blank=True, null=True, verbose_name='总工作量节数')),
                ('workload_score', models.FloatField(blank=True, null=True, verbose_name='课时工作量成绩')),
                ('personal_score', models.FloatField(blank=True, default=0, null=True, verbose_name='教师个人成绩')),
                ('class_score', models.FloatField(blank=True, default=0, null=True, verbose_name='班级量化成绩')),
                ('group_score', models.FloatField(blank=True, default=0, null=True, verbose_name='教研组量化成绩')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总成绩')),
                ('rank', models.FloatField(blank=True, null=True, verbose_name='名次')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否公布')),
                ('attend_score', models.FloatField(blank=True, null=True, verbose_name='出勤成绩')),
                ('invigilation_score', models.FloatField(blank=True, null=True, verbose_name='监考成绩')),
                ('assess_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessdepart', verbose_name='此次参与考核部门')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.semester', verbose_name='学期')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.teacher', verbose_name='教师')),
                ('term_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.termtype', verbose_name='学期考核类型')),
            ],
            options={
                'verbose_name': '文化课教师期末考核成绩',
                'verbose_name_plural': '文化课教师期末考核成绩',
            },
        ),
        migrations.CreateModel(
            name='TeacherMidAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week', models.IntegerField()),
                ('class_hours', models.IntegerField(blank=True, default=0, null=True, verbose_name='课时节数')),
                ('duty_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='值班节数折算')),
                ('extra_work_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='额外工作节数折算')),
                ('total_workload', models.FloatField(blank=True, null=True, verbose_name='总工作量节数')),
                ('workload_score', models.FloatField(blank=True, null=True, verbose_name='课时工作量成绩')),
                ('personal_score', models.FloatField(blank=True, default=0, null=True, verbose_name='教师个人成绩')),
                ('class_score', models.FloatField(blank=True, default=0, null=True, verbose_name='班级量化成绩')),
                ('group_score', models.FloatField(blank=True, default=0, null=True, verbose_name='教研组量化成绩')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总成绩')),
                ('rank', models.FloatField(blank=True, null=True, verbose_name='名次')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否公布')),
                ('assess_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessdepart', verbose_name='此次参与考核部门')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.semester', verbose_name='学期')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.teacher', verbose_name='教师')),
                ('term_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.termtype', verbose_name='学期考核类型')),
            ],
            options={
                'verbose_name': '文化课教师期中考核成绩',
                'verbose_name_plural': '文化课教师期中考核成绩',
            },
        ),
        migrations.CreateModel(
            name='TeacherSemesterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='学期总成绩')),
                ('rank', models.FloatField(blank=True, null=True, verbose_name='学期名次')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_published', models.BooleanField(default=False)),
                ('assess_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessdepart', verbose_name='此次参与考核部门')),
                ('final_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_score', to='assessments.teacherfinalaccess', verbose_name='期末成绩')),
                ('mid_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_score', to='assessments.teachermidaccess', verbose_name='期中成绩')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.semester', verbose_name='学期')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.teacher', verbose_name='教师')),
                ('term_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.termtype', verbose_name='学期考核类型')),
            ],
            options={
                'verbose_name': '文化课教师学期总评成绩',
                'verbose_name_plural': '文化课教师学期总评成绩',
                'unique_together': {('teacher', 'semester')},
            },
        ),
    ]
