# Generated by Django 5.2 on 2025-06-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessdepart',
            options={'verbose_name': '参与考核部门', 'verbose_name_plural': '参与考核部门'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': '学期', 'verbose_name_plural': '学期'},
        ),
        migrations.AlterModelOptions(
            name='termtype',
            options={'verbose_name': '考核类型', 'verbose_name_plural': '考核类型'},
        ),
    ]
