# Generated by Django 5.2 on 2025-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessdepart_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artteachersemesterassess',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
        migrations.AddField(
            model_name='groupleadersemester',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
        migrations.AddField(
            model_name='headerteachersemester',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
        migrations.AddField(
            model_name='itteachersemester',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
        migrations.AddField(
            model_name='musicteachersemesterassess',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
        migrations.AddField(
            model_name='peteachersemester',
            name='assess_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='考核时间'),
        ),
    ]
