# Generated by Django 5.2 on 2025-06-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_artteachersemesterassess_assess_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peteacherfinalassess',
            name='workload_score',
            field=models.FloatField(blank=True, null=True, verbose_name='工作量成绩'),
        ),
        migrations.AddField(
            model_name='peteachermidassess',
            name='workload_score',
            field=models.FloatField(blank=True, null=True, verbose_name='工作量成绩'),
        ),
        migrations.AlterField(
            model_name='peteacherfinalassess',
            name='total_workload',
            field=models.FloatField(blank=True, null=True, verbose_name='总工作量节数'),
        ),
        migrations.AlterField(
            model_name='peteachermidassess',
            name='total_workload',
            field=models.FloatField(blank=True, null=True, verbose_name='总工作量节数'),
        ),
    ]
