# Generated by Django 5.2 on 2025-06-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_peteacherfinalassess_workload_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itteacherfinalassess',
            name='workload_score',
            field=models.FloatField(blank=True, null=True, verbose_name='工作量成绩'),
        ),
        migrations.AddField(
            model_name='itteachermidassess',
            name='workload_score',
            field=models.FloatField(blank=True, null=True, verbose_name='工作量成绩'),
        ),
        migrations.AlterField(
            model_name='itteacherfinalassess',
            name='total_workload',
            field=models.FloatField(blank=True, null=True, verbose_name='总工作量节数'),
        ),
        migrations.AlterField(
            model_name='itteachermidassess',
            name='total_workload',
            field=models.FloatField(blank=True, null=True, verbose_name='总工作量节数'),
        ),
    ]
