# Generated by Django 5.2 on 2025-06-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_itteacherfinalassess_workload_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerteacherfinalassess',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='headerteachermidassess',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
