# Generated by Django 5.2 on 2025-06-26 00:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_headerteacherfinalassess_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderTeacherMidAssess',
            new_name='HeadTeacherFinalAssess',
        ),
        migrations.RenameModel(
            old_name='HeaderTeacherFinalAssess',
            new_name='HeadTeacherMidAssess',
        ),
        migrations.RenameModel(
            old_name='HeaderTeacherSemester',
            new_name='HeadTeacherSemester',
        ),
        migrations.AlterModelOptions(
            name='headteacherfinalassess',
            options={'verbose_name': '班主任期末考核成绩', 'verbose_name_plural': '班主任期末考核成绩'},
        ),
        migrations.AlterModelOptions(
            name='headteachermidassess',
            options={'verbose_name': '班主任中期考核成绩', 'verbose_name_plural': '班主任中期考核成绩'},
        ),
    ]
