# Generated by Django 5.2 on 2025-06-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_rename_headerteachermidassess_headteacherfinalassess_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='headteacherfinalassess',
            unique_together={('semester', 'term_type', 'class_number')},
        ),
        migrations.AlterUniqueTogether(
            name='headteachermidassess',
            unique_together={('semester', 'term_type', 'class_number')},
        ),
        migrations.AlterUniqueTogether(
            name='headteachersemester',
            unique_together={('semester', 'term_type', 'class_number')},
        ),
        migrations.AlterField(
            model_name='headteachersemester',
            name='final_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_score', to='assessments.headteacherfinalassess', verbose_name='期末成绩'),
        ),
        migrations.AlterField(
            model_name='headteachersemester',
            name='mid_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_score', to='assessments.headteachermidassess', verbose_name='期中成绩'),
        ),
    ]
