# Generated by Django 5.2 on 2025-06-27 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_headteacherfinalassess_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aladmin',
            name='al_depart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='后勤科室'),
        ),
        migrations.AlterUniqueTogether(
            name='deputyheadteacher',
            unique_together={('teacher', 'semester')},
        ),
    ]
