# Generated by Django 5.2 on 2025-06-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_eduadmin_grade_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduadmin',
            name='grade_depart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='年级部'),
        ),
    ]
