# Generated by Django 5.2 on 2025-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_eduadmin_grade_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicteacherfinalassess',
            name='art_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='下学期艺考赋分'),
        ),
    ]
