# Generated by Django 5.2 on 2025-06-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_musicteacherfinalassess_art_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='artteacherfinalassess',
            name='art_score',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='下学期艺考赋分'),
        ),
    ]
