# Generated by Django 5.2 on 2025-06-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_artteacherfinalassess_art_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='aladmin',
            name='term_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.termtype', verbose_name='考核类型'),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='term_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.termtype', verbose_name='考核类型'),
        ),
    ]
