# Generated by Django 5.2 on 2025-06-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='appointment_grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分级竞聘后聘任等级'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='appointment_grade_time',
            field=models.CharField(blank=True, null=True, verbose_name='分级竞聘后聘任时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='第一学历'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_education_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='第一学历专业'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_education_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='第一学历毕业院校'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_education_time',
            field=models.CharField(blank=True, null=True, verbose_name='第一学历毕业时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最高学历'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_education_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最高学历专业'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_education_school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最高学历毕业院校'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highest_education_time',
            field=models.CharField(blank=True, null=True, verbose_name='最高学历毕业时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='party_time',
            field=models.CharField(blank=True, null=True, verbose_name='入党时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='professional_qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业资格'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='professional_qualification_time',
            field=models.CharField(blank=True, null=True, verbose_name='专业资格取得时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='聘任职称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='professional_title_time',
            field=models.CharField(blank=True, null=True, verbose_name='聘任时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='transfer_time',
            field=models.CharField(blank=True, null=True, verbose_name='调入我校时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='work_time',
            field=models.CharField(blank=True, null=True, verbose_name='参加工作时间'),
        ),
    ]
