# Generated by Django 5.2 on 2025-05-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
    ]
