# Generated by Django 5.2 on 2025-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
