# Generated by Django 5.2 on 2025-06-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo_appointment_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
