# Generated by Django 5.2 on 2025-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='现住址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='native_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='political_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='政治面貌'),
        ),
    ]
