# Generated by Django 5.2 on 2025-07-03 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='出生日期'),
        ),
    ]
