# Generated by Django 5.2 on 2025-07-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='first_education_time',
            field=models.DateField(blank=True, null=True, verbose_name='第一学历毕业时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='highest_education_time',
            field=models.DateField(blank=True, null=True, verbose_name='最高学历毕业时间'),
        ),
    ]
