# Generated by Django 5.2 on 2025-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='party_time',
            field=models.DateField(blank=True, null=True, verbose_name='入党时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_time',
            field=models.DateField(blank=True, null=True, verbose_name='参加工作时间'),
        ),
    ]
