# Generated by Django 5.2 on 2025-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userinfo_party_time_alter_userinfo_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='appointment_grade_time',
            field=models.DateField(blank=True, null=True, verbose_name='分级竞聘后聘任时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='professional_qualification_time',
            field=models.DateField(blank=True, null=True, verbose_name='专业资格取得时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='professional_title_time',
            field=models.DateField(blank=True, null=True, verbose_name='聘任时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='transfer_time',
            field=models.DateField(blank=True, null=True, verbose_name='调入我校时间'),
        ),
    ]
